### ISSUE TITLE
Error: scale: must be a finite number

### ISSUE THREAD

**Issue by ramasDM** [MrPrimate/tokenizer#171]
Foundry VTT: Version 12 Build 328
Game System: DnD 3.2.1
Tokenizer: 4.3.10
libWrapper: 1.12.13.1

Steps to reproduce:
- create Avatar by uploading picture
- create Token, apply
- click Prototype Token and try to Update Token

Error stack:
foundry.js:71791 validation errors:
  prototypeToken: 
    ring: 
      subject: 
        scale: must be a finite number
foundry.js:631 Error: Actor5e [mRrAay90sMivgxJP] validation errors:
  prototypeToken: 
    ring: 
      subject: 
        scale: must be a finite number
    at DataModelValidationFailure.asError (foundry-esm.js:4710:14)
    at Actor5e.validate (foundry-esm.js:10416:61)
    at Actor5e.updateSource (foundry-esm.js:10486:12)
    at #preUpdateDocumentArray (foundry-esm.js:56455:22)
    at async ClientDatabaseBackend._updateDocuments (foundry-esm.js:56397:7)
    at async Actor5e.updateDocuments (foundry-esm.js:11457:23)
    at async Actor5e.update (foundry-esm.js:11567:23)
    at async TokenConfig5e._onSubmit (foundry.js:6640:7)

Alternative stack trace from other crash:
2foundry-esm.js:4710 Uncaught (in promise) Error: TokenDocument5e [GHBJSjXnBu4IyLSe] validation errors:
  ring: 
    subject: 
      scale: must be a finite number
    at DataModelValidationFailure.asError (foundry-esm.js:4710:14)
    at TokenDocument5e.validate (foundry-esm.js:10416:61)
    at TokenDocument5e.updateSource (foundry-esm.js:10486:12)
    at TokenDocument5e.updateSource (foundry-esm.js:16425:26)
    at TokenConfig5e._previewChanges (foundry.js:85393:20)
    at TokenConfig5e._previewChanges (token-config.mjs:170:11)
    at TokenConfig5e._onChangeInput (foundry.js:85377:10)
asError @ foundry-esm.js:4710
validate @ foundry-esm.js:10416
updateSource @ foundry-esm.js:10486
updateSource @ foundry-esm.js:16425
_previewChanges @ foundry.js:85393
_previewChanges @ token-config.mjs:170
_onChangeInput @ foundry.js:85377
await in _onChangeInput (async)
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
foundry.js:71791 validation errors:
  ring: 
    subject: 
      scale: must be a finite number

**Comment by MrPrimate** [comment]
I can't replicate this. Does this happen if all other modules are disabled? I don't set the scale for a token when saving, so I wonder if something else is interfering.

**Comment by ramasDM** [comment]
Tried slightly from further and I was able to Create New Actor, NPC actor, upload image, make token, update prototype without errors. 

It appears that I can still reproduce it when using Plutonium import. Import at Actors, chose Creatures - 5etools - Commoner. Do the same procedure - upload image, make token, update prototype gives an error message.

**Comment by MrPrimate** [comment]
Please contact the modules owner for troubleshooting.
